version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/stats-service
    image: ewm-stats-service
    container_name: stats-server
    ports:
      - "9090:9090"
    #      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - STATS_DB_URL=jdbc:postgresql://stats-db:5432/stats-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  #      - TZ=Europe/Moscow

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  #      - TZ=Europe/Moscow

  ewm-service:
    build: ewm-main-service/main-server
    image: ewm-main-service
    container_name: main-server
    ports:
      - "8080:8080"
    #      - "8081:8081"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - EWM_DB_URL=jdbc:postgresql://ewm-db:5432/ewm-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  #      - TZ=Europe/Moscow

  ewm-db:
    image: postgres:14.3-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#      - TZ=Europe/Moscow
